### ISSUE TITLE
No longer working, OS X 10.12

### ISSUE THREAD

**Issue by Fofer** [w0lfschild/NotificationClear#1]
I've just updated to macOS Sierra (10.12) and NotificationClear is no longer working for me.  Most of my other SIMBL add-ons seem fine.  Any pointers?

**Comment by w0lfschild** [comment]
Should still work. It's working fine for me on 10.12.3

Just make sure that NoticificationCenter is actually being injected into.

**Comment by Fofer** [comment]
Turns out I had been running an older version of NotificationClear (and mySIMBL wasn't reporting a newer version available.)  I manually updated, and now it's working again.  Thanks!
